name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [22]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Install Soufflé from source
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y cmake clang bison flex libffi-dev libncurses5-dev \
            libtinfo-dev libboost-all-dev libsqlite3-dev zlib1g-dev
    
          git clone https://github.com/souffle-lang/souffle.git
          cd souffle
          git checkout tags/2.4
          ./bootstrap
          ./configure
          make -j$(nproc)
          sudo make install
      
          souffle --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run Misti
        run: yarn misti --min-severity medium /path/to/your/tact.config.json
